export const AUTH_SUCCESS="AUTHSUCCESS";
export const AUTH_FAIL="AUTHFAIL";
export const AUTH_STATUS="AUTHSTATUS";
export const VERIFY_OTP_SUCCESS="VERIFYOTPSUCCESS";
export const VERIFY_OTP_FAIL="VERIFYOTPFAIL";
export const RESEND_OTP_SUCCESS="RESENDSUCCESS";
export const RESEND_OTP_FAIL="RESENDFAIL";